### ISSUE TITLE
Research how to create or run ML models using TensorFlow or PyTorch library 

### ISSUE THREAD

**Issue by NickWebber21** [ekelch/music#10]
meachine keranign everytrhing not kerrigan from starcraft

**Comment by ekelch** [comment]
![firefox_8DP9XywAGI](https://github.com/user-attachments/assets/03ddf020-557b-449b-98dc-d8d6fba294b0)

**Comment by NickWebber21** [comment]
Help

**Comment by NickWebber21** [comment]
TensorFlow/PyTorch (for emotion recognition model)
TensorFlow is a Python library that enables you to create and run ML models in any environment.
PyTorch is a free and open-source software library for machine learning and deep learning, based on the Torch library and developed by Meta AI. It supports tensor computing, neural networks, automatic differentiation, and various GPU platforms.

**Comment by NickWebber21** [comment]
Forget pytorch and tensorflow we're now going to be implementing **fisherfaces** which is more accurate than its competitors (eigenfaces) and (local binary patterns histogram) because eigenfaces considers illumination as a major feature of faces which can actually end up discarding peoples features. Where fisherfaces "extracts principle components that separates one individual from another" basically is better because now we can more fairly distribute the data, and also lighting wont matter too much.
